services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: backend/API/Dockerfile
    ports:
      - 5000:8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Agenda;User Id=sa;Password=DotNet@2025;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - SA_PASSWORD=DotNet@2025
    depends_on:
        sqlserver:
          condition: service_healthy
    networks:
      - dev_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DotNet@2025
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P 'DotNet@2025' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 60s
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - dev_network

volumes:
  sqlserver_data:
    external: true

networks:
  dev_network:
    external: true
