version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/app/backend
    depends_on:
      - sqlserver

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:80"
    # Aqui você pode ajustar conforme o seu projeto frontend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DotNet@2025!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
